"""Report generator — produces human-readable risk reports from RiskReport data.

Supports three output formats:
- Plain text (terminal-friendly)
- HTML (browser-friendly with inline styles)
- Terminal heatmap (compact section-by-section view)
"""

from __future__ import annotations

import html
import re

from ..shared.models import RiskReport, RiskLevel, Severity


class ReportGenerator:
    """Generates formatted reports from risk analysis results."""

    def generate_text(self, report: RiskReport) -> str:
        """Generate a plain-text report suitable for terminal display.

        Args:
            report: The RiskReport to render.

        Returns:
            A multi-line string with the full report.
        """
        lines = []
        lines.append("=" * 60)
        lines.append("OPEN TENDER CORRUPTION RISK REPORT")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"Tender: {report.tender.title}")
        if report.tender.reference_no:
            lines.append(f"Reference: {report.tender.reference_no}")
        if report.tender.procuring_entity:
            lines.append(
                f"Procuring Entity: {report.tender.procuring_entity}"
            )
        if report.tender.estimated_value:
            lines.append(
                f"Estimated Value: {report.tender.estimated_value}"
            )
        lines.append("")
        lines.append(
            f"OVERALL RISK: {self._format_risk(report.overall_risk)}"
        )
        lines.append("")

        # ── Section scores ──────────────────────────────────────────
        lines.append("-" * 60)
        lines.append("SECTION RISK SCORES:")
        lines.append("-" * 60)
        for section, score in report.section_scores.items():
            icon = self._risk_emoji(score)
            name = section.replace("_", " ").title()
            lines.append(f"  {icon} {name}: {score.upper()}")
        lines.append("")

        # ── Flagged clauses ─────────────────────────────────────────
        if report.flagged_clauses:
            lines.append("-" * 60)
            lines.append("FLAGGED CLAUSES / RED FLAGS:")
            lines.append("-" * 60)
            for i, flag in enumerate(report.flagged_clauses, 1):
                severity_icon = self._severity_icon(flag.severity)
                lines.append("")
                lines.append(
                    f"  #{i} {severity_icon} "
                    f"[{flag.severity.upper()}] {flag.label}"
                )
                lines.append(f"     {flag.description}")
                if flag.law_reference:
                    lines.append(f"     Law: {flag.law_reference}")
                lines.append(f"     Location: {flag.location}")
                lines.append(f"     Suggestion: {flag.suggestion}")
                if flag.excerpt:
                    cleaned = self._clean_excerpt(flag.excerpt)
                    if cleaned:
                        excerpt = cleaned[:150] + ("..." if len(cleaned) > 150 else "")
                        lines.append(f'     Excerpt: "{excerpt}"')
        else:
            lines.append("No red flags detected.")

        lines.append("")
        lines.append("=" * 60)
        lines.append(
            "Report generated by OpenTender + Counsel"
            " — AI-assisted analysis"
        )
        lines.append("=" * 60)

        return "\n".join(lines)

    # ── Nepali translations ────────────────────────────────────────
    _SECTION_NE = {
        "details": "विवरण",
        "specification": "विशिष्टीकरण",
        "budget": "बजेट",
        "timeline": "समयसीमा",
        "evaluation_criteria": "मूल्याङ्कन मापदण्ड",
        "terms_and_conditions": "सर्तहरू",
    }

    _RISK_NE = {
        "red": "उच्च जोखिम",
        "yellow": "मध्यम जोखिम",
        "green": "कम जोखिम",
    }

    _SEVERITY_NE = {
        "critical": "गम्भीर",
        "high": "उच्च",
        "medium": "मध्यम",
        "low": "न्यून",
    }

    _LOCATION_NE = {
        "Evaluation Criteria section": "मूल्याङ्कन मापदण्ड खण्ड",
        "Specification section": "विशिष्टीकरण खण्ड",
        "Budget section": "बजेट खण्ड",
        "Timeline section": "समयसीमा खण्ड",
        "Terms and Conditions section": "सर्तहरू खण्ड",
        "Document body": "कागजात मुख्य भाग",
        "Entire document": "सम्पूर्ण कागजात",
        "Details section": "विवरण खण्ड",
    }

    _CLAUSE_NE = {
        "timeline-too-short": {
            "label": "संदिग्ध रूपमा छोटो समयसीमा",
            "description": "बोलपत्र पेश गर्ने अवधि अत्यन्तै छोटो छ, जसले वैध बोलपत्रकर्ताहरूलाई बोलपत्र तयार गर्नबाट वञ्चित गर्न सक्छ।",
            "risk_reason": "धेरै छोटो समयसीमाले वैध बोलपत्रकर्ताहरूलाई बोलपत्र तयार गर्नबाट रोक्छ, जुन खरिद धाँधलीको सबैभन्दा सामान्य तरिका हो।",
            "suggestion": "न्यूनतम बोलपत्र अवधि सामान्यतया राष्ट्रिय खरिदको लागि १४-२५ दिन र अन्तर्राष्ट्रिय खरिदको लागि ४० दिन हुनुपर्छ।",
        },
        "single-brand-spec": {
            "label": "एकल ब्रान्ड / विशेष विशिष्टीकरण",
            "description": "विशिष्टीकरणले कुनै विशेष ब्रान्ड वा मोडललाई 'वा सो सरह' उल्लेख नगरी निर्दिष्ट गरेको छ।",
            "risk_reason": "विशेष विशिष्टीकरणले अन्य सबै आपूर्तिकर्ताहरूलाई बाहिर राख्छ, जसले गर्दा प्रतिस्पर्धा समाप्त हुन्छ र ठेक्का कुनै विशेष विक्रेतालाई मात्र दिइन्छ।",
            "suggestion": "विशिष्टीकरण सामान्य/प्रदर्शन-आधारित हुनुपर्छ। ब्रान्ड-विशिष्ट विशिष्टीकरणले प्रतिस्पर्धालाई सीमित गर्छ।",
        },
        "budget-inflation": {
            "label": "सम्भावित बजेट वृद्धि",
            "description": "बजेटमा ठूलो राउन्ड रकम, लागत विवरणको अभाव, वा अस्पष्ट बजेट भाषा पाइयो।",
            "risk_reason": "बढाइएको बजेटले किकब्याक, अधिक बिलिङ र हिनामिनाको अवसर सिर्जना गर्छ।",
            "suggestion": "इकाई दर र परिमाण सहितको विस्तृत लागत विवरण माग गर्नुहोस्।",
        },
        "opaque-evaluation": {
            "label": "अस्पष्ट मूल्याङ्कन मापदण्ड",
            "description": "मूल्याङ्कन मापदण्डमा विशिष्ट स्कोरिङ विधि वा तौलको अभाव छ।",
            "risk_reason": "प्रकाशित मूल्याङ्कन मापदण्ड बिना, मूल्याङ्कनकर्ताहरू जवाफदेही हुँदैनन् र मनपरी रूपमा विजेता छान्न सकिन्छ।",
            "suggestion": "मूल्याङ्कनमा स्पष्ट, परिमाणात्मक मापदण्ड र तौल समावेश हुनुपर्छ।",
        },
        "missing-evaluation-section": {
            "label": "मूल्याङ्कन खण्ड नभएको",
            "description": "बोलपत्र कागजातमा मूल्याङ्कन मापदण्ड खण्ड नै समावेश गरिएको छैन।",
            "risk_reason": "मूल्याङ्कन मापदण्ड लुकाउनु सबैभन्दा गम्भीर रेड फ्ल्याग हो। यसले कसरी ठेक्का दिइन्छ भन्ने कुरामा पारदर्शिता हुँदैन।",
            "suggestion": "प्रत्येक बोलपत्रले स्पष्ट मूल्याङ्कन मापदण्ड प्रकाशित गर्नुपर्छ। यो गम्भीर प्रक्रियागत उल्लङ्घन हो।",
        },
        "emergency-keywords": {
            "label": "औचित्य बिना आपतकालीन खरिद",
            "description": "कागजातमा आपतकालीन खरिद उल्लेख गरिएको छ तर औचित्य प्रदान गरिएको छैन।",
            "risk_reason": "आपतकालीन खरिदले मानक प्रतिस्पर्धात्मक बोलपत्र प्रक्रियालाई छल्छ, जुन भ्रष्टाचार विरुद्धको प्रमुख सुरक्षा हो।",
            "suggestion": "आपतकालीन खरिदको लागि विशेष औचित्य सहितको औपचारिक घोषणा आवश्यक छ।",
        },
        "vague-spec": {
            "label": "अस्पष्ट वा प्रतिलिपि गरिएको विशिष्टीकरण",
            "description": "प्राविधिक विशिष्टीकरण अस्पष्ट छ वा प्लेसहोल्डर भाषा समावेश गर्दछ।",
            "risk_reason": "अस्पष्ट विशिष्टीकरणले काम आवश्यकता अनुसार भए/नभएको मूल्याङ्कन गर्न असम्भव बनाउँछ।",
            "suggestion": "विशिष्टीकरण विस्तृत, मापनयोग्य र प्रमाणित गर्न सकिने हुनुपर्छ।",
        },
        "conflict-interest-signals": {
            "label": "हितको द्वन्द्वको सम्भावित संकेत",
            "description": "सर्तहरूमा हितको द्वन्द्व वा अयोग्यता सम्बन्धी प्रावधानहरू फेला परेनन्।",
            "risk_reason": "हितको द्वन्द्व नियम बिना, खरिद अधिकारीहरूले आफ्ना आफन्त वा व्यावसायिक साझेदारहरूलाई कानुनी परिणाम बिना ठेक्का दिन सक्छन्।",
            "suggestion": "मानक खरिद कागजातमा हितको द्वन्द्व र अयोग्यता सम्बन्धी खण्डहरू समावेश हुनुपर्छ।",
        },
        "unusual-contract-terms": {
            "label": "असामान्य वा एकपक्षीय सम्झौता सर्तहरू",
            "description": "सम्झौता सर्तहरूमा जरिवाना, धरौटी, वा निरीक्षण जस्ता मानक प्रावधानहरू हटाइएको पाइयो।",
            "risk_reason": "जरिवाना, ग्यारेन्टी वा निरीक्षण हटाउने एकपक्षीय सर्तहरूले गैर-प्रदर्शनको कुनै परिणाम राख्दैन।",
            "suggestion": "मानक खरिद सम्झौतामा जरिवाना खण्ड, प्रदर्शन ग्यारेन्टी र निरीक्षण अधिकार समावेश हुनुपर्छ।",
        },
    }

    def generate_text_ne(self, report: RiskReport) -> str:
        """Generate a plain-text report entirely in Nepali."""
        lines = []
        lines.append("=" * 60)
        lines.append("खुला बोलपत्र भ्रष्टाचार जोखिम प्रतिवेदन")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"बोलपत्र: {report.tender.title}")
        if report.tender.reference_no:
            lines.append(f"सन्दर्भ: {report.tender.reference_no}")
        if report.tender.procuring_entity:
            lines.append(f"खरिद निकाय: {report.tender.procuring_entity}")
        if report.tender.estimated_value:
            lines.append(f"अनुमानित मूल्य: {report.tender.estimated_value}")
        lines.append("")
        lines.append(
            f"कुल जोखिम: {self._RISK_NE.get(report.overall_risk.value, report.overall_risk.upper())}"
        )
        lines.append("")

        # ── Section scores ──────────────────────────────────────────
        lines.append("-" * 60)
        lines.append("खण्डगत जोखिम स्कोर:")
        lines.append("-" * 60)
        for section, score in report.section_scores.items():
            icon = self._risk_emoji(score)
            name = self._SECTION_NE.get(section, section.replace("_", " ").title())
            risk_text = self._RISK_NE.get(score.value, score.upper())
            lines.append(f"  {icon} {name}: {risk_text}")
        lines.append("")

        # ── Flagged clauses ─────────────────────────────────────────
        if report.flagged_clauses:
            lines.append("-" * 60)
            lines.append("चिन्हित खण्डहरू / रेड फ्ल्यागहरू:")
            lines.append("-" * 60)
            for i, flag in enumerate(report.flagged_clauses, 1):
                ne_data = self._CLAUSE_NE.get(flag.red_flag_id, {})
                ne_label = ne_data.get("label", flag.label)
                ne_desc = ne_data.get("description", flag.description)
                ne_reason = ne_data.get("risk_reason", flag.risk_reason)
                ne_sugg = ne_data.get("suggestion", flag.suggestion)

                severity_icon = self._severity_icon(flag.severity)
                sev_label = self._SEVERITY_NE.get(flag.severity.value, flag.severity.upper())
                lines.append("")
                lines.append(f"  #{i} {severity_icon} [{sev_label}] {ne_label}")
                lines.append(f"     {ne_desc}")
                if flag.law_reference:
                    lines.append(f"     कानुन: {flag.law_reference}")
                loc_ne = self._LOCATION_NE.get(flag.location, flag.location)
                lines.append(f"     स्थान: {loc_ne}")
                lines.append(f"     सुझाव: {ne_sugg}")
                if flag.excerpt:
                    cleaned = self._clean_excerpt(flag.excerpt)
                    if cleaned:
                        excerpt = cleaned[:150] + ("..." if len(cleaned) > 150 else "")
                        lines.append(f'     उद्धरण: "{excerpt}"')
        else:
            lines.append("कुनै रेड फ्ल्याग पत्ता लागेन।")

        lines.append("")
        lines.append("=" * 60)
        lines.append(
            "यो प्रतिवेदन OpenTender + Counsel द्वारा तयार गरिएको हो"
            " — एआई-सहायता प्राप्त विश्लेषण"
        )
        lines.append("=" * 60)

        return "\n".join(lines)

    def generate_html(self, report: RiskReport) -> str:
        """Generate a minimal self-contained HTML report for browser viewing.

        Uses inline styles so no external CSS is required.

        Args:
            report: The RiskReport to render.

        Returns:
            A complete HTML document as a string.
        """
        # ── Section scores HTML ─────────────────────────────────────
        score_html = ""
        for section, score in report.section_scores.items():
            name = html.escape(section.replace("_", " ").title())
            color = self._risk_color(score)
            score_html += (
                '    <div style="display:flex;'
                'justify-content:space-between;'
                'padding:6px 0;border-bottom:1px solid #eee;">'
                f"<span>{name}</span>"
                f'<span style="color:{color};font-weight:bold;">'
                f"{score.upper()}</span></div>\n"
            )

        # ── Flagged clauses HTML ────────────────────────────────────
        flags_html = ""
        for flag in report.flagged_clauses:
            color = self._severity_color(flag.severity)
            law_ref = (
                f'<div><b>Law:</b> {html.escape(flag.law_reference)}</div>'
                if flag.law_reference
                else ""
            )
            flags_html += f"""
    <div style="border-left:4px solid {color};padding:12px;
                margin:12px 0;background:#f9f9f9;border-radius:4px;">
        <div style="font-weight:bold;color:{color};">
            {html.escape(flag.label)} [{flag.severity.upper()}]
        </div>
        <div style="margin:6px 0;">{html.escape(flag.description)}</div>
        <div style="font-size:0.9em;color:#666;">
            {law_ref}
            <div><b>Location:</b> {html.escape(flag.location)}</div>
            <div><b>Suggestion:</b> {html.escape(flag.suggestion)}</div>
        </div>
    </div>"""

        overall_color = self._risk_color(report.overall_risk)

        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Risk Report - {html.escape(report.tender.title[:60])}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI',
       Roboto, sans-serif; max-width: 800px; margin: 20px auto;
       padding: 0 20px; color: #222; }}
h1 {{ font-size: 1.5em; }}
.badge {{ display:inline-block; padding:4px 12px; border-radius:20px;
         color:white; font-weight:bold; font-size:1.1em; }}
</style></head>
<body>
<h1>🛡️ OpenTender + Counsel — Corruption Risk Report</h1>
<table style="width:100%; margin:12px 0;">
    <tr><td><b>Tender:</b></td>
        <td>{html.escape(report.tender.title)}</td></tr>
    {f'<tr><td><b>Reference:</b></td><td>{html.escape(report.tender.reference_no)}</td></tr>' if report.tender.reference_no else ''}
    {f'<tr><td><b>Entity:</b></td><td>{html.escape(report.tender.procuring_entity)}</td></tr>' if report.tender.procuring_entity else ''}
    {f'<tr><td><b>Value:</b></td><td>{html.escape(report.tender.estimated_value)}</td></tr>' if report.tender.estimated_value else ''}
</table>

<div style="margin:20px 0;padding:20px;background:#f0f0f0;
            border-radius:8px;text-align:center;">
    <div style="font-size:0.9em;color:#666;">Overall Risk Level</div>
    <div class="badge" style="background:{overall_color};
         font-size:1.5em;margin:8px 0;">
        {report.overall_risk.upper()}
    </div>
</div>

<h2>Section Scores</h2>
{score_html}

<h2>Red Flags ({len(report.flagged_clauses)})</h2>
{flags_html if flags_html else '<p>No red flags detected. ✓</p>'}

<hr style="margin:30px 0;">
<div style="font-size:0.8em;color:#999;text-align:center;">
    Generated by OpenTender + Counsel — AI-assisted corruption
    risk analysis. This is not legal advice. Consult a qualified
    attorney for legal action.
</div>
</body></html>"""

    def generate_heatmap(self, report: RiskReport) -> str:
        """Generate a compact section-by-section risk heatmap.

        Terminal-friendly; uses emoji bars for colour.

        Args:
            report: The RiskReport to render.

        Returns:
            A multi-line string with the heatmap.
        """
        lines = []
        lines.append("")
        lines.append("  RISK HEATMAP")
        lines.append("  " + "─" * 40)

        sections_in_order = [
            "details",
            "specification",
            "budget",
            "timeline",
            "evaluation_criteria",
            "terms_and_conditions",
        ]
        for section in sections_in_order:
            score = report.section_scores.get(section, RiskLevel.GREEN)
            name = section.replace("_", " ").title()
            bar = self._risk_bar(score)
            lines.append(f"  {bar} {name}")

        lines.append("  " + "─" * 40)
        overall = report.overall_risk
        bar = self._risk_bar(overall)
        lines.append(f"  {bar} OVERALL: {overall.upper()}")
        lines.append("")
        return "\n".join(lines)

    # ── Formatting helpers ──────────────────────────────────────────

    def _format_risk(self, level: RiskLevel) -> str:
        """Format a risk level with an emoji prefix."""
        icon = self._risk_emoji(level)
        return f"{icon} {level.upper()}"

    def _risk_emoji(self, level: RiskLevel) -> str:
        """Return a coloured-circle emoji for a risk level."""
        return {"green": "🟢", "yellow": "🟡", "red": "🔴"}.get(
            level.value, "⚪"
        )

    def _severity_icon(self, severity: Severity) -> str:
        """Return an icon emoji for a severity level."""
        return {
            "low": "ℹ️",
            "medium": "⚠️",
            "high": "🚨",
            "critical": "💀",
        }.get(severity.value, "⚪")

    # Helper to clean excerpt text for readability
    def _clean_excerpt(self, text: str) -> str:
        """Sanitize excerpt text: keep alphanumerics, Devanagari, basic punctuation.
        Collapse whitespace and filter out obvious OCR noise.
        """
        cleaned = re.sub(r'[^A-Za-z0-9\u0900-\u097F\s.,;:!?\-\'\"]+', ' ', text)
        cleaned = re.sub(r'\s+', ' ', cleaned).strip()
        # Discard very short or empty excerpts – they are usually garbled PDF noise
        if len(cleaned) < 20:
            return ''
        # Discard common PDF page markers (e.g., "--- Page 1 ---")
        if cleaned.lower().startswith('--- page'):
            return ''
        # Tokenize for further heuristics
        tokens = cleaned.split()
        if not tokens:
            return ''
        # Existing average‑token‑length heuristic (still useful)
        avg_len = sum(len(tok) for tok in tokens) / len(tokens)
        if avg_len < 3.0:
            return ''
        # ---- New noise detection heuristics ----
        # Ratio of non‑alphanumeric characters (punctuation, symbols)
        non_alpha_ratio = sum(1 for c in cleaned if not c.isalnum()) / len(cleaned)
        # Count tokens that contain at least one alphabetic character (Latin or Devanagari)
        alpha_token_count = sum(1 for t in tokens if re.search(r'[A-Za-z\u0900-\u097F]', t))
        # Ratio of single‑character tokens (often OCR artefacts)
        single_char_ratio = sum(1 for t in tokens if len(t) == 1) / len(tokens)
        # If any of the following indicate noise, discard the excerpt
        if (
            non_alpha_ratio > 0.4 or
            alpha_token_count < 3 or
            single_char_ratio > 0.5 or
            (len(tokens) > 30 and (non_alpha_ratio > 0.2 or single_char_ratio > 0.3))
        ):
            return ''
        return cleaned

    def _risk_color(self, level: RiskLevel) -> str:
        """Return a CSS hex colour for a risk level."""
        return {"green": "#22c55e", "yellow": "#eab308", "red": "#ef4444"}.get(
            level.value, "#999"
        )

    def _severity_color(self, severity: Severity) -> str:
        """Return a CSS hex colour for a severity level."""
        return {
            "low": "#6b7280",
            "medium": "#eab308",
            "high": "#f97316",
            "critical": "#ef4444",
        }.get(severity.value, "#999")

    def _risk_bar(self, level: RiskLevel) -> str:
        """Return a coloured-circle emoji (alias for _risk_emoji)."""
        return self._risk_emoji(level)
