/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConstitutionRouteImport } from './routes/constitution'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnalysisReportRouteImport } from './routes/analysis-report'
import { Route as IndexRouteImport } from './routes/index'

const ConstitutionRoute = ConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisReportRoute = AnalysisReportRouteImport.update({
  id: '/analysis-report',
  path: '/analysis-report',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis-report': typeof AnalysisReportRoute
  '/chat': typeof ChatRoute
  '/constitution': typeof ConstitutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis-report': typeof AnalysisReportRoute
  '/chat': typeof ChatRoute
  '/constitution': typeof ConstitutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis-report': typeof AnalysisReportRoute
  '/chat': typeof ChatRoute
  '/constitution': typeof ConstitutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analysis-report' | '/chat' | '/constitution'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analysis-report' | '/chat' | '/constitution'
  id: '__root__' | '/' | '/analysis-report' | '/chat' | '/constitution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisReportRoute: typeof AnalysisReportRoute
  ChatRoute: typeof ChatRoute
  ConstitutionRoute: typeof ConstitutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/constitution': {
      id: '/constitution'
      path: '/constitution'
      fullPath: '/constitution'
      preLoaderRoute: typeof ConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis-report': {
      id: '/analysis-report'
      path: '/analysis-report'
      fullPath: '/analysis-report'
      preLoaderRoute: typeof AnalysisReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisReportRoute: AnalysisReportRoute,
  ChatRoute: ChatRoute,
  ConstitutionRoute: ConstitutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
